/// GENERATED BY ./scripts/generate_bridge
import SwiftUI
public final class UniBridge: @unchecked Sendable {
    public static let shared = UniBridge()
    private init() {}
    public enum IntType: Int32, Sendable {
        case lensFlare = 0
        case facialExpression = 1
        case objectSelected = 2
        case qualityLevel = 3
    }
    public let intMapper = ValueBinding<Int32, IntType>()
    public private(set) lazy var lensFlare = intMapper.set(.lensFlare)
    public private(set) lazy var facialExpression = intMapper.set(.facialExpression)
    public var objectSelected: Binding<Int32> { intMapper.binding(.objectSelected) }
    public private(set) lazy var qualityLevel = intMapper.set(.qualityLevel)

    public enum FloatType: Int32, Sendable {
        case camera = 0
        case light = 1
        case postExposure = 2
        case whiteBalanceTemperature = 3
        case whiteBalanceTint = 4
        case saturation = 5
        case hueShift = 6
        case contrast = 7
        case bloomIntensity = 8
        case bloomThreshold = 9
        case bloomSoftKnee = 10
        case bloomDiffusion = 11
        case bloomAnamorphicRatio = 12
        case bloomLensFlareIntensity = 13
        case vignetteIntensity = 14
        case vignetteSmoothness = 15
        case vignetteRoundness = 16
        case lipSyncMicIntensity = 17
        case micAudioLevel = 18
        case fps = 19
        case shoulderRotationWeight = 20
        case swivelOffset = 21
        case trackingSmoothing = 22
    }
    public let floatMapper = ValueBinding<CGFloat, FloatType>()
    public private(set) lazy var camera = floatMapper.set(.camera)
    public private(set) lazy var light = floatMapper.set(.light)
    public private(set) lazy var postExposure = floatMapper.set(.postExposure)
    public private(set) lazy var whiteBalanceTemperature = floatMapper.set(.whiteBalanceTemperature)
    public private(set) lazy var whiteBalanceTint = floatMapper.set(.whiteBalanceTint)
    public private(set) lazy var saturation = floatMapper.set(.saturation)
    public private(set) lazy var hueShift = floatMapper.set(.hueShift)
    public private(set) lazy var contrast = floatMapper.set(.contrast)
    public private(set) lazy var bloomIntensity = floatMapper.set(.bloomIntensity)
    public private(set) lazy var bloomThreshold = floatMapper.set(.bloomThreshold)
    public private(set) lazy var bloomSoftKnee = floatMapper.set(.bloomSoftKnee)
    public private(set) lazy var bloomDiffusion = floatMapper.set(.bloomDiffusion)
    public private(set) lazy var bloomAnamorphicRatio = floatMapper.set(.bloomAnamorphicRatio)
    public private(set) lazy var bloomLensFlareIntensity = floatMapper.set(.bloomLensFlareIntensity)
    public private(set) lazy var vignetteIntensity = floatMapper.set(.vignetteIntensity)
    public private(set) lazy var vignetteSmoothness = floatMapper.set(.vignetteSmoothness)
    public private(set) lazy var vignetteRoundness = floatMapper.set(.vignetteRoundness)
    public private(set) lazy var lipSyncMicIntensity = floatMapper.set(.lipSyncMicIntensity)
    public private(set) lazy var micAudioLevel = floatMapper.set(.micAudioLevel)
    public private(set) lazy var fps = floatMapper.set(.fps)
    public private(set) lazy var shoulderRotationWeight = floatMapper.set(.shoulderRotationWeight)
    public private(set) lazy var swivelOffset = floatMapper.set(.swivelOffset)
    public private(set) lazy var trackingSmoothing = floatMapper.set(.trackingSmoothing)

    public enum BoolType: Int32, Sendable {
        case useAutoMode = 0
        case useShadow = 1
        case usePostEffect = 2
        case useCombineMesh = 3
        case useAddToMacOSMenuBar = 4
        case useVSync = 5
        case useNewTracking = 6
        case useBlinker = 7
        case useFullTracking = 8
        case lipSyncWebCam = 9
        case hasPerfectSyncBlendShape = 10
    }
    public let boolMapper = ValueBinding<Bool, BoolType>()
    public private(set) lazy var useAutoMode = boolMapper.set(.useAutoMode)
    public private(set) lazy var useShadow = boolMapper.set(.useShadow)
    public private(set) lazy var usePostEffect = boolMapper.set(.usePostEffect)
    public private(set) lazy var useCombineMesh = boolMapper.set(.useCombineMesh)
    public private(set) lazy var useAddToMacOSMenuBar = boolMapper.set(.useAddToMacOSMenuBar)
    public private(set) lazy var useVSync = boolMapper.set(.useVSync)
    public private(set) lazy var useNewTracking = boolMapper.set(.useNewTracking)
    public private(set) lazy var useBlinker = boolMapper.set(.useBlinker)
    public private(set) lazy var useFullTracking = boolMapper.set(.useFullTracking)
    public private(set) lazy var lipSyncWebCam = boolMapper.set(.lipSyncWebCam)
    public var hasPerfectSyncBlendShape: Bool { boolMapper.get(.hasPerfectSyncBlendShape) }

    public enum StringType: Int32, Sendable {
        case message = 0
        case loadVRM = 1
        case loadModel = 2
        case showEmojiStamp = 3
    }
    public let stringMapper = ValueBinding<String, StringType>()
    public private(set) lazy var message = stringMapper.set(.message)
    public private(set) lazy var loadVRM = stringMapper.set(.loadVRM)
    public private(set) lazy var loadModel = stringMapper.set(.loadModel)
    public private(set) lazy var showEmojiStamp = stringMapper.set(.showEmojiStamp)

    public enum TriggerType: Int32, Sendable {
        case openVRoidHub = 0
        case resetCamera = 1
        case deleteObject = 2
        case resetAllObjects = 3
        case editAvatar = 4
        case pauseApp = 5
        case resumeApp = 6
        case quitApp = 7
    }
    public let triggerMapper = ValueBinding<Void, TriggerType>()
    public private(set) lazy var openVRoidHub = triggerMapper.trigger(.openVRoidHub)
    public private(set) lazy var resetCamera = triggerMapper.trigger(.resetCamera)
    public private(set) lazy var deleteObject = triggerMapper.trigger(.deleteObject)
    public private(set) lazy var resetAllObjects = triggerMapper.trigger(.resetAllObjects)
    public private(set) lazy var editAvatar = triggerMapper.trigger(.editAvatar)
    public private(set) lazy var pauseApp = triggerMapper.trigger(.pauseApp)
    public private(set) lazy var resumeApp = triggerMapper.trigger(.resumeApp)
    public private(set) lazy var quitApp = triggerMapper.trigger(.quitApp)

    public enum StructType: Int32, Sendable {
        case backgroundColor = 0
        case environmentLightColor = 1
        case colorFilter = 2
        case bloomColor = 3
        case vignetteColor = 4
    }
    public let structMapper = ValueBinding<UnsafeMutableRawPointer, StructType>()
    public private(set) lazy var backgroundColor = structMapper.set(.backgroundColor, type: Color.self)
    public private(set) lazy var environmentLightColor = structMapper.set(.environmentLightColor, type: Color.self)
    public private(set) lazy var colorFilter = structMapper.set(.colorFilter, type: Color.self)
    public private(set) lazy var bloomColor = structMapper.set(.bloomColor, type: Color.self)
    public private(set) lazy var vignetteColor = structMapper.set(.vignetteColor, type: Color.self)

    public enum ArrayType: Int32, Sendable {
        case hands = 0
        case fingers = 1
        case receiveVCamBlendShape = 2
        case receivePerfectSync = 3
        case addRenderTexture = 4
        case updateRenderTexture = 5
        case updateObjectOrder = 6
        case setObjectActive = 7
        case setObjectLocked = 8
        case objectAvatarTransform = 9
        case addWind = 10
        case canvasSize = 11
        public var arraySize: Int {
            switch self {
            case .hands: return 12
            case .fingers: return 10
            case .receiveVCamBlendShape: return 12
            case .receivePerfectSync: return 60
            case .addRenderTexture: return 8
            case .updateRenderTexture: return 3
            case .updateObjectOrder: return 99
            case .setObjectActive: return 2
            case .setObjectLocked: return 2
            case .objectAvatarTransform: return 6
            case .addWind: return 4
            case .canvasSize: return 2
            }
        }
    }
    public let arrayMapper = ValueBinding<UnsafeMutableRawPointer, ArrayType>()
    public private(set) lazy var hands = arrayMapper.set(.hands, type: [Float].self)
    public private(set) lazy var fingers = arrayMapper.set(.fingers, type: [Float].self)
    public private(set) lazy var receiveVCamBlendShape = arrayMapper.set(.receiveVCamBlendShape, type: [Float].self)
    public private(set) lazy var receivePerfectSync = arrayMapper.set(.receivePerfectSync, type: [Float].self)
    public private(set) lazy var addRenderTexture = arrayMapper.set(.addRenderTexture, type: [Int32].self)
    public private(set) lazy var updateRenderTexture = arrayMapper.set(.updateRenderTexture, type: [Int32].self)
    public private(set) lazy var updateObjectOrder = arrayMapper.set(.updateObjectOrder, type: [Int32].self)
    public private(set) lazy var setObjectActive = arrayMapper.set(.setObjectActive, type: [Int32].self)
    public private(set) lazy var setObjectLocked = arrayMapper.set(.setObjectLocked, type: [Int32].self)
    public private(set) lazy var objectAvatarTransform = arrayMapper.set(.objectAvatarTransform, type: [Float].self)
    public private(set) lazy var addWind = arrayMapper.set(.addWind, type: [Int32].self)
    public var canvasSize: [Float] { arrayMapper.get(.canvasSize, size: 2) }

}
