/// GENERATED BY ./scripts/generate_bridge
import SwiftUI
@MainActor
public final class UniBridge {
    public static let shared = UniBridge()
    private init() {}
    public enum IntType: Int32, Sendable {
        case lensFlare = 0
        case facialExpression = 1
        case qualityLevel = 2
    }
    public let intMapper = ValueBinding<Int32, IntType>()
    public private(set) lazy var facialExpression = intMapper.set(.facialExpression)

    public enum FloatType: Int32, Sendable {
        case light = 0
        case postExposure = 1
        case whiteBalanceTemperature = 2
        case whiteBalanceTint = 3
        case saturation = 4
        case hueShift = 5
        case contrast = 6
        case bloomIntensity = 7
        case bloomThreshold = 8
        case bloomSoftKnee = 9
        case bloomDiffusion = 10
        case bloomAnamorphicRatio = 11
        case bloomLensFlareIntensity = 12
        case vignetteIntensity = 13
        case vignetteSmoothness = 14
        case vignetteRoundness = 15
        case lipSyncMicIntensity = 16
        case micAudioLevel = 17
        case fps = 18
        case shoulderRotationWeight = 19
        case swivelOffset = 20
        case trackingSmoothing = 21
        case bodyFollowWeight = 22
    }
    public let floatMapper = ValueBinding<CGFloat, FloatType>()
    public private(set) lazy var micAudioLevel = floatMapper.set(.micAudioLevel)

    public enum BoolType: Int32, Sendable {
        case useShadow = 0
        case usePostEffect = 1
        case useCombineMesh = 2
        case useAddToMacOSMenuBar = 3
        case useVSync = 4
        case useBlinker = 5
        case useFullTracking = 6
        case lipSyncWebCam = 7
        case avatarHidden = 8
        case hasPerfectSyncBlendShape = 9
    }
    public let boolMapper = ValueBinding<Bool, BoolType>()
    public private(set) lazy var useBlinker = boolMapper.set(.useBlinker)
    public private(set) lazy var useFullTracking = boolMapper.set(.useFullTracking)
    public private(set) lazy var avatarHidden = boolMapper.set(.avatarHidden)
    public var hasPerfectSyncBlendShape: Bool { boolMapper.get(.hasPerfectSyncBlendShape) }

    public enum StringType: Int32, Sendable {
        case loadModel = 0
    }
    public let stringMapper = ValueBinding<String, StringType>()
    public private(set) lazy var loadModel = stringMapper.set(.loadModel)

    public enum TriggerType: Int32, Sendable {
        case resetCamera = 0
        case removeAllWinds = 1
        case pauseApp = 2
        case resumeApp = 3
        case quitApp = 4
    }
    public let triggerMapper = ValueBinding<Void, TriggerType>()
    public private(set) lazy var resetCamera = triggerMapper.trigger(.resetCamera)
    public private(set) lazy var removeAllWinds = triggerMapper.trigger(.removeAllWinds)
    public private(set) lazy var pauseApp = triggerMapper.trigger(.pauseApp)
    public private(set) lazy var resumeApp = triggerMapper.trigger(.resumeApp)
    public private(set) lazy var quitApp = triggerMapper.trigger(.quitApp)

    public enum StructType: Int32, Sendable {
        case environmentLightColor = 0
        case colorFilter = 1
        case bloomColor = 2
        case vignetteColor = 3
    }
    public let structMapper = ValueBinding<UnsafeMutableRawPointer, StructType>()

    public enum ArrayType: Int32, Sendable {
        case hands = 0
        case fingers = 1
        case receiveVCamBlendShape = 2
        case receivePerfectSync = 3
        case objectAvatarTransform = 4
        case addWind = 5
        case removeWind = 6

        public var elementCount: Int {
            switch self {
            case .hands: 12
            case .fingers: 10
            case .receiveVCamBlendShape: 12
            case .receivePerfectSync: 60
            case .objectAvatarTransform: 7
            case .addWind: 4
            case .removeWind: 1
            }
        }
    }
    public let arrayMapper = ValueBinding<UnsafeMutableRawPointer, ArrayType>()
    public private(set) lazy var hands = arrayMapper.set(.hands, type: [Float].self)
    public private(set) lazy var fingers = arrayMapper.set(.fingers, type: [Float].self)
    public private(set) lazy var receiveVCamBlendShape = arrayMapper.set(.receiveVCamBlendShape, type: [Float].self)
    public private(set) lazy var receivePerfectSync = arrayMapper.set(.receivePerfectSync, type: [Float].self)
    public private(set) lazy var objectAvatarTransform = arrayMapper.set(.objectAvatarTransform, type: [Float].self)
    public private(set) lazy var addWind = arrayMapper.set(.addWind, type: [Int32].self)
    public private(set) lazy var removeWind = arrayMapper.set(.removeWind, type: [Int32].self)

}
