/// GENERATED BY ./scripts/generate_bridge
import SwiftUI
@MainActor
public final class UniBridge {
    public static let shared = UniBridge()
    private init() {}
    public enum IntType: Int32, Sendable {
        case lensFlare = 0
        case facialExpression = 1
        case qualityLevel = 2
    }
    public let intMapper = ValueBinding<Int32, IntType>()
    public private(set) lazy var lensFlare = intMapper.set(.lensFlare)
    public private(set) lazy var facialExpression = intMapper.set(.facialExpression)
    public private(set) lazy var qualityLevel = intMapper.set(.qualityLevel)

    public enum FloatType: Int32, Sendable {
        case camera = 0
        case light = 1
        case postExposure = 2
        case whiteBalanceTemperature = 3
        case whiteBalanceTint = 4
        case saturation = 5
        case hueShift = 6
        case contrast = 7
        case bloomIntensity = 8
        case bloomThreshold = 9
        case bloomSoftKnee = 10
        case bloomDiffusion = 11
        case bloomAnamorphicRatio = 12
        case bloomLensFlareIntensity = 13
        case vignetteIntensity = 14
        case vignetteSmoothness = 15
        case vignetteRoundness = 16
        case lipSyncMicIntensity = 17
        case micAudioLevel = 18
        case fps = 19
        case shoulderRotationWeight = 20
        case swivelOffset = 21
        case trackingSmoothing = 22
    }
    public let floatMapper = ValueBinding<CGFloat, FloatType>()
    public private(set) lazy var camera = floatMapper.set(.camera)
    public private(set) lazy var light = floatMapper.set(.light)
    public private(set) lazy var postExposure = floatMapper.set(.postExposure)
    public private(set) lazy var whiteBalanceTemperature = floatMapper.set(.whiteBalanceTemperature)
    public private(set) lazy var whiteBalanceTint = floatMapper.set(.whiteBalanceTint)
    public private(set) lazy var saturation = floatMapper.set(.saturation)
    public private(set) lazy var hueShift = floatMapper.set(.hueShift)
    public private(set) lazy var contrast = floatMapper.set(.contrast)
    public private(set) lazy var bloomIntensity = floatMapper.set(.bloomIntensity)
    public private(set) lazy var bloomThreshold = floatMapper.set(.bloomThreshold)
    public private(set) lazy var bloomSoftKnee = floatMapper.set(.bloomSoftKnee)
    public private(set) lazy var bloomDiffusion = floatMapper.set(.bloomDiffusion)
    public private(set) lazy var bloomAnamorphicRatio = floatMapper.set(.bloomAnamorphicRatio)
    public private(set) lazy var bloomLensFlareIntensity = floatMapper.set(.bloomLensFlareIntensity)
    public private(set) lazy var vignetteIntensity = floatMapper.set(.vignetteIntensity)
    public private(set) lazy var vignetteSmoothness = floatMapper.set(.vignetteSmoothness)
    public private(set) lazy var vignetteRoundness = floatMapper.set(.vignetteRoundness)
    public private(set) lazy var lipSyncMicIntensity = floatMapper.set(.lipSyncMicIntensity)
    public private(set) lazy var micAudioLevel = floatMapper.set(.micAudioLevel)
    public private(set) lazy var fps = floatMapper.set(.fps)
    public private(set) lazy var shoulderRotationWeight = floatMapper.set(.shoulderRotationWeight)
    public private(set) lazy var swivelOffset = floatMapper.set(.swivelOffset)
    public private(set) lazy var trackingSmoothing = floatMapper.set(.trackingSmoothing)

    public enum BoolType: Int32, Sendable {
        case useShadow = 0
        case usePostEffect = 1
        case useCombineMesh = 2
        case useAddToMacOSMenuBar = 3
        case useVSync = 4
        case useBlinker = 5
        case useFullTracking = 6
        case lipSyncWebCam = 7
        case avatarHidden = 8
        case hasPerfectSyncBlendShape = 9
    }
    public let boolMapper = ValueBinding<Bool, BoolType>()
    public private(set) lazy var useShadow = boolMapper.set(.useShadow)
    public private(set) lazy var usePostEffect = boolMapper.set(.usePostEffect)
    public private(set) lazy var useCombineMesh = boolMapper.set(.useCombineMesh)
    public private(set) lazy var useAddToMacOSMenuBar = boolMapper.set(.useAddToMacOSMenuBar)
    public private(set) lazy var useVSync = boolMapper.set(.useVSync)
    public private(set) lazy var useBlinker = boolMapper.set(.useBlinker)
    public private(set) lazy var useFullTracking = boolMapper.set(.useFullTracking)
    public private(set) lazy var lipSyncWebCam = boolMapper.set(.lipSyncWebCam)
    public private(set) lazy var avatarHidden = boolMapper.set(.avatarHidden)
    public var hasPerfectSyncBlendShape: Bool { boolMapper.get(.hasPerfectSyncBlendShape) }

    public enum StringType: Int32, Sendable {
        case loadModel = 0
    }
    public let stringMapper = ValueBinding<String, StringType>()
    public private(set) lazy var loadModel = stringMapper.set(.loadModel)

    public enum TriggerType: Int32, Sendable {
        case resetCamera = 0
        case removeAllWinds = 1
        case pauseApp = 2
        case resumeApp = 3
        case quitApp = 4
    }
    public let triggerMapper = ValueBinding<Void, TriggerType>()
    public private(set) lazy var resetCamera = triggerMapper.trigger(.resetCamera)
    public private(set) lazy var removeAllWinds = triggerMapper.trigger(.removeAllWinds)
    public private(set) lazy var pauseApp = triggerMapper.trigger(.pauseApp)
    public private(set) lazy var resumeApp = triggerMapper.trigger(.resumeApp)
    public private(set) lazy var quitApp = triggerMapper.trigger(.quitApp)

    public enum StructType: Int32, Sendable {
        case environmentLightColor = 0
        case colorFilter = 1
        case bloomColor = 2
        case vignetteColor = 3
    }
    public let structMapper = ValueBinding<UnsafeMutableRawPointer, StructType>()
    public private(set) lazy var environmentLightColor = structMapper.set(.environmentLightColor, type: Color.self)
    public private(set) lazy var colorFilter = structMapper.set(.colorFilter, type: Color.self)
    public private(set) lazy var bloomColor = structMapper.set(.bloomColor, type: Color.self)
    public private(set) lazy var vignetteColor = structMapper.set(.vignetteColor, type: Color.self)

    public enum ArrayType: Int32, Sendable {
        case hands = 0
        case fingers = 1
        case receiveVCamBlendShape = 2
        case receivePerfectSync = 3
        case objectAvatarTransform = 4
        case addWind = 5
        case removeWind = 6
    }
    public let arrayMapper = ValueBinding<UnsafeMutableRawPointer, ArrayType>()
    public private(set) lazy var hands = arrayMapper.set(.hands, type: [Float].self)
    public private(set) lazy var fingers = arrayMapper.set(.fingers, type: [Float].self)
    public private(set) lazy var receiveVCamBlendShape = arrayMapper.set(.receiveVCamBlendShape, type: [Float].self)
    public private(set) lazy var receivePerfectSync = arrayMapper.set(.receivePerfectSync, type: [Float].self)
    public private(set) lazy var objectAvatarTransform = arrayMapper.set(.objectAvatarTransform, type: [Float].self)
    public private(set) lazy var addWind = arrayMapper.set(.addWind, type: [Int32].self)
    public private(set) lazy var removeWind = arrayMapper.set(.removeWind, type: [Int32].self)

}
